import { constructUrl } from "../constants/AGOL/preserve-maps/api";
import { constructUrl as walkMapConstructUrl } from "../constants/AGOL/walk-maps/api";
import { sources } from "../constants/dataMapping";
import { sources as walkMapSources } from "../constants/walk-map/dataMapping";


// #FIX - fetch this from the DB - 

export const InitialMapStates = (orgId : string | null, serviceName: string | null) => {
    return {
        'ThreeSistersPreserve': {
            id : 0,
            promotion: false,
            webMapName: "Three Sisters Preserve",
            owner: "Aidrondack Land Trust",
            logoURL: "img/raster/LeftSidebar/BadgeIcon.png",
            email : "giving@alt.org",
            cityAndState: "Wilmington, NY",
            center: [-73.8045, 44.3804],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [-73.80140, 44.38320],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: "./data/preserve_boundary.geojson",
                trails:  "./data/trails_updated.geojson",
                pois: "./data/pois.geojson",
                trailheads: "./data/trailheads.geojson",
                parkingLots: "./data/parking.geojson",
                distances: "./data/distances.geojson", 
                images: ["/img/raster/RightSidebar/heroImg.png", "/img/raster/RightSidebar/heroImg - Copy.png", "/img/raster/RightSidebar/heroImg - Copy2.png"],
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'SchumannPreserve': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [-73.61729, 43.46723],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson: null, 
        },

        'SchumannPreserve3D': {
            id : 1,
            promotion: true,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [-73.6171345851022, 43.46662609427642],
            zoom: 14.1,
            pitch: 41,
            bearing: 32.2,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson: null, 
        },

        'ThePinnaclePreserve': {
            id : 1,
            promotion: false,   
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [-73.67758, 43.556577],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            },
            preserveGeojson: null
        },

        'BerryPondPreserve': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [-73.75763, 43.40135],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'PeggysPoint': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.7450749,-73.4969596],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'LeemingJelliffePreserve': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.655792,-73.490481],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'GodwinPreserve': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.633178,-73.652584],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'TerzianWoodlotPreserve': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.678529,-73.517310],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'AnthonysNosePreserve': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.771863,-73.460716],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'CookMountain': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.817343,-73.446024],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'PoleHillPond': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.623369,-73.632015],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'SuckerBrook': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.750062,-73.449876],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'AmysParkPreserve': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.750062,-73.449876],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },

        'CatThomasMountainsPreserve': {
            id : 1,
            promotion: false,
            webMapName: null,
            owner: null,
            logoURL: null,
            email : null,
            cityAndState: "Fort Ann, NY",
            center: [43.750062,-73.449876],
            zoom: 14,
            pitch: 0,
            bearing: 0,
            minZoom: 10,
            maxZoom: 18,
            maxPitch: 70,
            bbox: false,
            donationPinCoords: [0,0],
            dataRefs: {
                masterTable: constructUrl({orgId, serviceName, layerId: 5}),
                preserve: constructUrl({orgId, serviceName, layerId: 3}),
                trails:  constructUrl({orgId, serviceName, layerId: 2}),
                pois: constructUrl({orgId, serviceName, layerId: 1}),
                trailheads: constructUrl({orgId, serviceName, layerId: 0}),
                parkingLots: constructUrl({orgId, serviceName, layerId: 4}),
                distances: null,
                images : null,
                trailSourceName: "trails-source",
                sourceNames: sources
            }, 
            preserveGeojson : null 
        },
        'walkmaps': {
          id : 1,
          promotion: false,
          webMapName: "Saranac River Walk",
          owner: 'Aidrondack Land Trust',
          logoURL: null,
          email : null,
          cityAndState: "Fort Ann, NY",
          center: [-74.13261610157, 44.3270],
          zoom: 15,
          pitch: 0,
          bearing: 0,
          minZoom: 2,
          maxZoom: 20,
          maxPitch: 70,
          // #Tamas 11. - here are the values being used for "Reset View" button - fly to method. My plan was to make this caculated on backend side as a bbox view somewhere, but we stopped working on that.. 
          // you can figure out how to calculate bbox for camera dynamically some what i did for preserve type.
          bbox: [-74.1362, 44.3275, -74.125, 44.3275],
          donationPinCoords: [0,0],
          /*
            #Tamas 1.- pay atention to layer ids in object below: this will be refactored and cleaned up, 
            but anyway you can find these ids in the AGOL feature hosted page info: [https://adkres.maps.arcgis.com/home/item.html?id=b37cb20ffbdb4c1abe1d242a915e0209]
            section called "Layers"
          */
          dataRefs: {
            masterTable: null,
            preserve: null,
            trails: walkMapConstructUrl({orgId, serviceName, layerId: 2}),
            pois: walkMapConstructUrl({orgId, serviceName, layerId: 1}),
            kiosks: walkMapConstructUrl({orgId, serviceName, layerId: 0}),
            trailheads: null,
            parkingLots: null,
            distances: null,
            images : null,
            trailSourceName: "trails-source",
            sourceNames: walkMapSources
          }, 
          preserveGeojson : null 
        }
    }
}
